### PR TITLE
feature: get the role from the jwt and assign talentmap role. TM-1350 TM-1351

### PR DESCRIPTION
**Pull request by rtirserio**
assigns correct role based on token role and removes any assignable roles from the user. talentmap specific roles (like superuser or glossary_editor are not impacted).

### CODE REVIEW

**Comment by mjoyce91** [comment]
Here's an old bit of functionality that needs to be changed in `talentmap_api/user_profile/models.py`:

```python
@property
    def is_cdo(self):
        '''
        Represents if the user is a CDO (Career development officer) or not. If the user's direct_report
        reverse relationship has any members, they are a CDO
        '''

        return self.direct_reports.count() != 0
```

Should probably just reference whether they have the CDO permission, regardless of `direct_reports` count.

**Comment by mjoyce91** [comment]
This is adding the role correctly, but isn't removing "stale" roles.

**Comment by rtirserio** [comment]
@mjoyce91 i updated the is_cdo function. Can you provided more info as to what you are seeing with not removing the stale roles?

**Comment by mjoyce91** [comment]
@rtirserio here's what I tried:

mock-fsbid DB:
By default, woodwardw role is set to CDO or CDO3

talentmap DB:
By default, woodward does not have the CDO permission

Step 1. Log in to TalentMAP with woodwardw. Log out of TalentMAP.
- Result: woodwardw now has the CDO permission in the talentmap DB
Step 2. Manually remove the CDO/CDO3 role in the mock-fsbid DB by changing the "role" value in the "employees" table to "blah".
Step 3. Log in as woodwardw.
- Result: woodwardw still has the CDO permission in the talentmap DB

**Comment by rtirserio** [comment]
@mjoyce91 i was able to verify this is working. its possible that the database updates you made weren't picked up by the container. What I had to do to make the updates to the mock_db is connect through the API container.
```
docker-compose run app bash
psql -U mockfsbid-user -h mock_db mockfsbid
<password in docker-compose yml>
update employees set role = <whatever> where perdet_seq_num = <whatever>
```
You can verify the role change in the talentmap db by...
```
docker-compose run app bash
psql -U talentmap-user -h db talentmap
select auth_user.username, auth_user.id, auth_group.name from auth_user join auth_user_groups on auth_user.id = auth_user_groups.user_id join auth_group on auth_user_groups.group_id = auth_group.id;
```

**Pull request merged**
