### PR TITLE
feature: favorites on projected vacancies. TM-641

### PR DESCRIPTION
**Pull request by rtirserio**
Saves projected vacancy position numbers and user ids. Fetches the actual projected vacancy from fsbid.

### CODE REVIEW

**Comment by rtirserio** [comment]
@mjoyce91 fixed the response shape

**Comment by mjoyce91** [comment]
@rtirserio thanks, structure looks good - however, now I'm getting the full response of all projected favorites, even if the user has not saved any projected vacancies as favorites:

Example when the projected_vacancies_projectedvacancyfavorite table is empty:

`GET /api/v1/projected_vacancy/favorites/`

```
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 1,
      ...
    },
    {
      "id": 2,
      ...
    },
  ]
}
```

**Comment by mjoyce91** [comment]
I guess more specifically, does FSBid have the capability to search by ID, for something like this?

`GET /api/v1/fsbid/projected_vacancies/2/`

**Comment by rtirserio** [comment]
Do it doesnt have that but it does allow for the position number to be passed. I was ignoring the filter since we werent using that for search so we need it here. Im in the process of getting it working on the mock and API

**Comment by rtirserio** [comment]
@mjoyce91 bring down the latest as well as a fix on the fsbid mock. you'll have to rebuild using docker-compose.

**Comment by mjoyce91** [comment]
@rtirserio when I run a query like this, I don't have any issues:

http://localhost:3333/projectedVacancies?positionNumber=1

But when I run it through the TalentMAP API, none of the query params get passed:

**Comment by mjoyce91** [comment]
@rtirserio thanks, this will work

**Pull request merged**
