### PR TITLE
WIP Pylint/circleci

### PR DESCRIPTION
**Pull request by mjoyce91**
- Adds pylint for linting
- Use autopep8 for auto-fixing (find and install appropriate plugin for your IDE)
  - You may need to follow these steps:
    - Install and set virtual env: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/
    - `pip install -r requirements.txt` from your API project folder
    - Set editor’s pylint executable to that path: ex: /Users/johnsmith/Documents/env/bin/pylint

### CODE REVIEW

**Comment by scott062** [comment]
Initially I thought I got the setup working on vscode, but I ended up getting the same error when I reimplemented what I had before with that settings file. For some reason, it can't find project specific module imports. I've tried a lot of fixes, but nothing works yet. If this is working for you, we can merge it and just work around those false positive import errors

**Comment by mjoyce91** [comment]
@scott062 - what we can also do is ignore the "import not found" rule for now.

**Comment by elizabeth-jimenez** [comment]
@scott062 @mjoyce91 Working on this for PyCharm 🤞

**Comment by scott062** [comment]
@mjoyce91 this works! 
Screen Shot 2020-07-06 at 9 19 38 AM

**Pull request merged**
