### PR TITLE
Use basic auth for Swagger even when SAML is enabled

### PR DESCRIPTION
**Pull request by mjoyce91**

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
Does this mean we no longer have to use a valid JWT, in Swagger, for the EPs that require it?

**Comment by mjoyce91** [comment]
@elizabeth-jimenez you know how sometimes when you open up a page in a new tab and you're "logged in", but don't have a JWT so nothing loads? This will fix that

**Comment by elizabeth-jimenez** [comment]
> @elizabeth-jimenez you know how sometimes when you open up a page in a new tab and you're "logged in", but don't have a JWT so nothing loads? This will fix that

ooohh nice!

**Review by elizabeth-jimenez — APPROVED** [review]
🍰 🍥 👍

**Pull request merged**
