### PR TITLE
Add create_obc command in order to load db with obc links

### PR DESCRIPTION
**Pull request by mjoyce91**
`python manage.py create_obc`

### CODE REVIEW

**Review by scott062 — COMMENTED** [review]
This worked Mike, but just wondering if we're able to move this into an existing command for setting up dev env - I haven't looked into it though, so if you already know then this is good to go. @elizabeth-jimenez @SidelineCory24 Just note that this is a subset of the locations being seeded so you won't see obc links for everything, right @mjoyce91 ?

**Comment by mjoyce91** [comment]
> This worked Mike, but just wondering if we're able to move this into an existing command for setting up dev env - I haven't looked into it though, so if you already know then this is good to go. @elizabeth-jimenez @SidelineCory24 Just note that this is a subset of the locations being seeded so you won't see obc links for everything, right @mjoyce91 ?

Yeah you're right, I should include this in create_demo_environment

**Comment by mjoyce91** [comment]
@scott062 - also included `create_base_permissions` since that should be there anyways

**Comment by scott062** [comment]
`create_demo_environment` worked as expected and I have all the roles and obc links - was able to UI test with no obvious errors 👍

**Review by scott062 — APPROVED** [review]

**Pull request merged**
