### PR TITLE
adding endpoints for scheduling data syncs as admin

### PR DESCRIPTION
**Pull request by joelhanson**
adding endpoints to edit SynchronizationJobs in DB and reset SynchronizationJob

### CODE REVIEW

**Comment by mjoyce91** [comment]
Looks like there are some extra fields here that don't relate to this endpoint:

Screen Shot 2019-07-12 at 2 07 30 PM

**Comment by mjoyce91** [comment]
For patching a data sync, these properties are not getting updated:

```
"last_synchronization"
"next_synchronization"
"delta_synchronization"
```

These work though:

```
"running"
"talentmap_model"
"priority"
```

This one isn't included in the sample request, but might be one that we want users to be able to configure:

``` 
"use_last_date_updated"
```

**Comment by mjoyce91** [comment]
@joelhanson what kind of date formats does the PATCH end point expect? I'm trying to set `"last_sync": "1978-01-01T00:00:00Z",` but the value doesn't update.

**Comment by joelhanson** [comment]
@mjoyce91 That date format is fine, but the field is called `last_synchronization` not `last_sync`

**Comment by mjoyce91** [comment]
@joelhanson ah okay. Can you update the swagger example request? I had just copy and pasted directly from there and then updated its values.

**Comment by joelhanson** [comment]
@mjoyce91 Not sure what you're looking at because the swagger request does say "last_synchronization" on my end. 
image

**Comment by mjoyce91** [comment]
Ohh never mind I see what I did. I didn't take the swagger response - I took the response from a `GET http://localhost:8000/api/v1/data_sync/` which uses `last_sync` and `next_sync` 😄

**Comment by mjoyce91** [comment]
What if we just updated those values to match for consistency's sake?

**Comment by joelhanson** [comment]
@mjoyce91 I'll update the `http://localhost:8000/api/v1/data_sync/` call and commit

**Pull request merged**
