### PR TITLE
fix: get TED and posted dates from cycle position. TM-1006

### PR DESCRIPTION
**Pull request by rtirserio**

### CODE REVIEW

**Comment by mjoyce91** [comment]
Screen Shot 2019-06-11 at 9 36 27 AM

Is the first one only null because my data wasn't imported via data sync?

**Comment by rtirserio** [comment]
@mjoyce91 correct. if you either manually enter something for the posted_date on cycle position OR rerun the import locally you'll see that its pulling the correct date

**Comment by mjoyce91** [comment]
@rtirserio So I re-ran the import, but it's still showing null - would that be because I'm using old data? I ran `python manage.py load_all_data /[path-to-csvs]`

**Comment by rtirserio** [comment]
@mjoyce91 yea its not updated in the csv files, you need to run the import from the XML imports

**Comment by mjoyce91** [comment]
@rtirserio Oh, actually I was using the XMLs. Maybe they're outdated? Are there newer ones?

**Comment by rtirserio** [comment]
@mjoyce91 i always had to run them all to get them to work.

`docker-compose run app python manage.py schedule_synchronization_job --list` to be sure you have them in the list.

SQL - `update integrations_synchronizationjob set next_synchronization = CURRENT_DATE - 50;`

then `docker-compose run app python manage.py synchronize_data --test --model bidding.BidCycle` to run the cycle positions

**Pull request merged**
