### PR TITLE
feature: adds position designations to cycle position stats. TM-695

### PR DESCRIPTION
**Pull request by rtirserio**
Adds new fields to the bid statistics and new endpoints for getting these values by a bid cycle and position, setting the values for a position within a bid cycle, and getting all designations for all positions in a cycle (filtering on values available)

### CODE REVIEW

**Comment by mjoyce91** [comment]
I noticed that no matter what `pos_id` I used for this request, the same position was returned in the response. Using a different `id` returned a different position, but there's no way to change the bid cycle. Is that expected behavior?

`GET /api/v1/bidcycle/{id}/position/{pos_id}/designation/`

**Comment by rtirserio** [comment]
@mjoyce91 fixed the issue you were seeing.

**Comment by mjoyce91** [comment]
@rtirserio I think the `pos_id` is still pointing to the bid cycle id.

`GET http://localhost:8000/api/v1/bidcycle/2/position/1/designation/` (bid cycle 2, position 1 (both exist)):
```
{
  "detail": "Not found."
}
```

http://localhost:8000/api/v1/bidcycle/999/position/1/designation/ correctly returns:

`BidCycle matching query does not exist.`

But the only way to get a response is to set both the bid cycle id and the position id to a bid cycle id that exists. So for me, this is the only way to get a response, since I have a bid cycle with id: 2:

`http://localhost:8000/api/v1/bidcycle/2/position/2/designation/`

**Comment by rtirserio** [comment]
@mjoyce91 - i added the 404 if the cycle or position are not found. let me know if you see any other issues

**Comment by mjoyce91** [comment]
@rtirserio I guess I'm still confused why `/api/v1/bidcycle/2/position/2/designation/` is the only request that returns anything. Every other request turns "Not found".

**Comment by rtirserio** [comment]
@mjoyce91 what do you get when you do GET `/api/v1/bidcycle/{id}/positions/` with a bid cycle id that you know exists?

**Comment by rtirserio** [comment]
@mjoyce91 @burgwyn - Lets wait until the merge for 1.1 gets in. This is going to change a bit due to the new model.

**Comment by rtirserio** [comment]
@mjoyce91 @burgwyn - ive updated this to use cycle position. This is ready for review

**Comment by burgwyn** [comment]
Check the merge conflicts @rtirserio

**Comment by rtirserio** [comment]
@burgwyn - conflicts resolved

**Comment by rtirserio** [comment]
@burgwyn @mjoyce91 can we get this reviewed and merged?

**Pull request merged**
