### PR TITLE
fix: update availability to use cycle position to allow bidding

### PR DESCRIPTION
**Pull request by rtirserio**
calculate availability for cycle position.

### CODE REVIEW

**Comment by mjoyce91** [comment]
Maybe unrelated since I think I've had this issue before, but I'm having trouble testing since I can't add positions to my bid list:

```
IntegrityError at /api/v1/bidlist/position/259/
null value in column "is_hard_to_fill" violates not-null constraint
DETAIL:  Failing row contains (262, PositionBidStatistics object (None), 0, 0, 0, 0, 259, f, f, null, null, null).
```

**Comment by mjoyce91** [comment]
I tried manually adding an entry to `bidding_bid` but still getting availability: true

**Comment by rtirserio** [comment]
@mjoyce91 a position is still available even if it has a bid. there would need to be a bid that is handshake offered or beyond. i was able to submit a bid without error. you need to use the cycle position id as the param

**Comment by mjoyce91** [comment]
@rtirserio I've added the following row to `bidding_bid`. Converted to json to make it easier to read:

```json
  {
    "id": 118,
    "_string_representation": null,
    "status": "handshake_offered",
    "draft_date": "2006-09-20 00:00:00+00",
    "submitted_date": "2006-09-20 00:00:00+00",
    "handshake_offered_date": "2006-09-20 00:00:00+00",
    "handshake_accepted_date": "2006-09-20 00:00:00+00",
    "handshake_declined_date": null,
    "in_panel_date": null,
    "scheduled_panel_date": "2006-09-20 00:00:00+00",
    "approved_date": null,
    "declined_date": null,
    "closed_date": null,
    "is_priority": true,
    "panel_reschedule_count": 0,
    "create_date": "2006-09-20 00:00:00+00",
    "update_date": "2006-09-20 00:00:00+00",
    "bidcycle_id": 12,
    "position_id": 259,
    "reviewer_id": 2,
    "user_id": 2
  }
```

Even so, the response from /api/v1/cycleposition/259/ is:

```json
{
  "id": 259,
  "status": "Open",
  "status_code": "OP",
  "ted": "2018-07-02 05:00:00+00:00",
  "posted_date": "2018-01-22 06:45:05+00:00",
  "availability": {
    "availability": true,
    "reason": ""
  },
  "created": "2017-01-25T22:47:46Z",
  "updated": "2018-01-22T06:45:05Z",
  "bidcycle": {
    "id": 12,
    "name": "Now & Winter 2017/2018",
    "cycle_start_date": "2017-11-01T05:00:00Z",
    "cycle_deadline_date": "2020-03-06T05:00:00Z",
    "cycle_end_date": "2020-04-30T05:00:00Z",
    "active": true
  },
  "position": {
    "id": 102,
    "grade": "02",
    "skill": "FOREIGN BUILDINGS (2324)",
    "bureau": "(OPS/AM/WHA) WESTERN HEMISPHERE AREA DIVISION",
    "organization": "(OPS/AM/WHA) WESTERN HEMISPHERE AREA DIVISION",
    "tour_of_duty": null,
    "classifications": [],
    "representation": "[S6451313] FOREIGN BUILDINGS OFFICER (Washington, DC)",
    "availability": {
      "availability": true,
      "reason": ""
    },
    "position_number": "S6451313",
    "title": "FOREIGN BUILDINGS OFFICER",
    "is_overseas": false,
    "is_highlighted": false,
    "create_date": "2006-09-20T00:00:00Z",
    "update_date": "2017-06-08T00:00:00Z",
    "effective_date": "2018-01-22T06:45:05Z",
    "posted_date": "2018-01-22T06:45:05Z",
    "description": {
      "id": 48,
      "last_editing_user": null,
      "is_editable_by_user": false,
      "date_created": "2019-03-05T20:01:04.079373Z",
      "date_updated": "2019-03-05T20:13:19.515543Z",
      "content": "The incumbent is one of five Area Management Officers (AMOs) in the Western Hemisphere and Americas (WHA) Division of the Area Management Office (AM) in the Bureau of Overseas Buildings Operations.  AMOs serve as the primary liaison between overseas posts and the Bureau of Overseas Buildings Operations (OBO) on property acquisition and leasing, construction, facility management, and physical security issues.  Their overseas experience is invaluable in conveying the unique requirements of U.S. overseas missions to official Washington.  AMOs work closely with OBO staff, regional bureau officials, Diplomatic Security, the Under Secretary for Management, and the intelligence community on issues related to the acquisition, construction, and management of USG diplomatic facilities.   Frequent travel to overseas locations is required.  The incumbent reports to and works under the general direction of the geographical area division chief.   \r\nPOC: Bevan Benjamin, 703-875-6939 (BenjaminB@state.gov).  Revised 08/29/2016.\r\n",
      "point_of_contact": null,
      "website": null
    },
    "current_assignment": {
      "user": "Doe",
      "tour_of_duty": null,
      "status": "active",
      "start_date": "2019-03-05T20:09:25.208168Z",
      "estimated_end_date": "2018-07-03T05:00:00Z"
    },
    "post": {
      "id": 281,
      "code": "110010001",
      "tour_of_duty": null,
      "cost_of_living_adjustment": 0,
      "differential_rate": 0,
      "danger_pay": 0,
      "rest_relaxation_point": "",
      "has_consumable_allowance": false,
      "has_service_needs_differential": false,
      "obc_id": "304",
      "location": {
        "id": 4,
        "country": "United States",
        "code": "110010001",
        "city": "Washington",
        "state": "DC"
      }
    },
    "latest_bidcycle": {
      "id": 2,
      "name": "Demo BidCycle 2019-03-05 20:09:18.408688+00:00",
      "cycle_start_date": "2018-12-05T20:09:18.408656Z",
      "cycle_deadline_date": "2099-04-05T20:09:18.408656Z",
      "cycle_end_date": "2099-06-05T20:09:18.408656Z",
      "active": false
    },
    "languages": []
  },
  "bid_statistics": null
}
```

**Comment by rtirserio** [comment]
@mjoyce91 the status needs to be either handshake_accepted, in_panel or approved for it to be a false value for the availability

**Comment by mjoyce91** [comment]
@rtirserio - updated to `handshake_accepted` and getting the same thing

**Comment by rtirserio** [comment]
@mjoyce91 - ok found the issue and fixed

**Pull request merged**
