### PR TITLE
Feature/get clients TM-1375

### PR DESCRIPTION
**Pull request by scott062**

### CODE REVIEW

**Comment by mjoyce91** [comment]
@scott062 can you resolve conflicts? `api/v1/fsbid/cdo/` vs `api/v1/fsbid/cdo`

**Comment by rtirserio** [comment]
@mjoyce91 - I took care of it, scott is in training and likely unavailable

**Comment by mjoyce91** [comment]
Can we update the description text to "get all clients"?

Screen Shot 2019-12-04 at 9 30 28 AM

**Comment by rtirserio** [comment]
@mjoyce91 see #255

**Comment by mjoyce91** [comment]
@scott062 @rtirserio I know this is merged, but lets look at mapping the skills codes into an array of objects:

```json
    "skill_code": null,
    "skill_code_desc": null,
    "skill2_code": null,
    "skill2_code_desc": null,
    "skill3_code": null,
    "skill3_code_desc": null,
```

**Comment by mjoyce91** [comment]
@rtirserio Also, can we get a `/client/:id` endpoint?

**Comment by rtirserio** [comment]
@mjoyce91 yes, does the FSBid client endpoint take any additional params other than ad_id?

**Comment by mjoyce91** [comment]
@rtirserio I'll check

**Pull request merged**
